// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    Education: typeof import('./components/Education.vue')['default']
    Experience: typeof import('./components/Experience.vue')['default']
    FirstView: typeof import('./components/FirstView.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HardSkills: typeof import('./components/Skills/HardSkills.vue')['default']
    PersonalInfo: typeof import('./components/PersonalInfo.vue')['default']
    README: typeof import('./components/README.md')['default']
    Skills: typeof import('./components/Skills.vue')['default']
    SoftSkills: typeof import('./components/Skills/SoftSkills.vue')['default']
    StaticHeader: typeof import('./components/StaticHeader.vue')['default']
    TeqnologiesLogos: typeof import('./components/TeqnologiesLogos.vue')['default']
  }
}

export { }
