// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./components/AboutMe.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Education: typeof import('./components/Education.vue')['default']
    Experience: typeof import('./components/Experience.vue')['default']
    FirstView: typeof import('./components/FirstView.vue')['default']
    FixHeader: typeof import('./components/FixHeader.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HardSkills: typeof import('./components/Skills/HardSkills.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    PersonalInfo: typeof import('./components/PersonalInfo.vue')['default']
    README: typeof import('./components/README.md')['default']
    Skills: typeof import('./components/Skills.vue')['default']
    SoftSkills: typeof import('./components/Skills/SoftSkills.vue')['default']
    StaticHeader: typeof import('./components/StaticHeader.vue')['default']
    TeqnologiesLogos: typeof import('./components/TeqnologiesLogos.vue')['default']
  }
}

export { }
